select
	ii.PRODUCT_ID ,
	ii.FACILITY_ID ,
	ii.QUANTITY_ON_HAND_TOTAL ,
	ii.AVAILABLE_TO_PROMISE_TOTAL,
	(ii.QUANTITY_ON_HAND_TOTAL -ii.AVAILABLE_TO_PROMISE_TOTAL) as DIFFERENCE
from
	inventory_item ii ;
