SELECT 
    oh.SALES_CHANNEL_ENUM_ID,
    COUNT(oh.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oh.GRAND_TOTAL) AS TOTAL_REVENUE,
    DATE_FORMAT(oh.ORDER_DATE, '%Y-%m') AS REPORTING_PERIOD
FROM 
    order_header oh
GROUP BY 
    oh.SALES_CHANNEL_ENUM_ID,
    DATE_FORMAT(oh.ORDER_DATE, '%Y-%m')
ORDER BY 
    REPORTING_PERIOD ASC;

